name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image olustur
        run: docker build -t nlaplmaz/todo-api:${{ github.sha }} .

      - name: Docker image push
        run: docker push nlaplmaz/todo-api:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container App'i guncelle
        run: |
          az containerapp update \
            --name todo-api-nly \
            --resource-group todo-api-rg \
            --image nlaplmaz/todo-api:${{ github.sha }}
